default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Postgre

development:
  <<: *default
  database: budget_app_development
  host: localhost


test:
  <<: *default
  database: budget_app_test


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>